version: "3.7"

services:
  postgres:
    image: kanlanc/humaine:production_17052021_postgres

    hostname: postgres
    container_name: postgres
    restart: always
    build:
      context: ./API/config
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: humaine
      DB_USER: postgres
      DB_PASSWORD: abc12345

    volumes:
      - humaine:/var/lib/postgresql/data
  api:
    env_file: "./API/.env"
    container_name: api
    restart: always
    build:
      context: ./API
      dockerfile: ./Dockerfile
    image: "kanlanc/humaine:production_17052021_api"
    depends_on:
      - postgres

    ports:
      - "4000:4000"

  ui:
    build:
      context: ./UI
      dockerfile: ./Dockerfile
    image: "kanlanc/humaine:production_17052021_ui"
    restart: always
    container_name: ui
    ports:
      - "80:80"

    depends_on:
      - api

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: a@a.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"

volumes:
  humaine:
