# This is for developement enviroment and react is not built and served with nginx

version: "3.7"

services:
  api:
    env_file: "./api/.env"
    container_name: api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: "kanlanc/humaine-api"
    ports:
      - "4000:4000"
  ui:
    build:
      context: ./ui
      dockerfile: ./Dockerfile.dev
    image: "kanlanc/humaine-ui-dev"
    container_name: ui-dev
    ports:
      - "80:3000"
    links:
      - "api:api"
