version: "3.7"

services:
  ##############################
  # Backend Container
  ##############################
  postgres:
    image: kanlanc/humaine:${DEV_TIMESTAMP}_postgres
    hostname: postgres
    container_name: postgres
    restart: always
    build:
      context: ./API/config
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: humaine
      DB_USER: postgres
      DB_PASSWORD: abc12345
      POSTGRES_PASSWORD: abc12345

    volumes:
      - humaine:/var/lib/postgresql/data
  api:
    env_file: "./API/.env"
    container_name: api
    restart: always
    build:
      context: ./API
      dockerfile: ./Dockerfile.dev
    image: "kanlanc/humaine:${DEV_TIMESTAMP}_api"
    depends_on:
      - postgres
    environment:
      CHOKIDAR_USEPOLLING: "true"

    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./API
        target: /app

  ##############################
  # UI Container
  ##############################
  ui:
    build:
      context: ./UI
      dockerfile: ./Dockerfile.dev
    restart: always
    image: "kanlanc/humaine:${DEV_TIMESTAMP}_ui"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    container_name: ui
    ports:
      - "80:3000"
      - "443:443"
    depends_on:
      - api
    volumes:
      - type: bind
        source: ./UI
        target: /app

  ##############################
  # Pgadmin Container
  ##############################
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  humaine:
