version: "3.7"

services:
  postgres:
    image: postgres:11.2-alpine
    hostname: postgres
    container_name: postgres
    restart: always
    build:
      context: ./API/config
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: humaine
      DB_USER: postgres
      DB_PASSWORD: abc12345

    volumes:
      - humaine:/var/lib/postgresql/data
      - ./API/config:/docker-entrypoint-initdb.d
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: a@a.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  api:
    env_file: "./API/.env"
    container_name: api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: "kanlanc/humaine-api"
    links:
      - postgres
    ports:
      - "4000:4000"
    # volumes:
    #   - ./API:/app
  ui:
    build:
      context: ./UI
      dockerfile: ./Dockerfile
    image: "kanlanc/humaine-ui"
    container_name: ui
    ports:
      - "80:80"
    # volumes:
    #   - ./UI:/app
    links:
      - "api:api"

volumes:
  humaine:
