version: "3.7"

services:
  ##############################
  # Backend Container
  ##############################
  api:
    container_name: api
    restart: always
    build:
      context: ./API
      dockerfile: ./Dockerfile
    image: "kanlanc/humaine:${PROD_TIMESTAMP}_api"
    ports:
      - "4000:4000"

  ##############################
  # UI Container
  ##############################
  ui:
    build:
      context: ./UI
      dockerfile: ./Dockerfile
    environment:
      API_URL: "/"

    image: "kanlanc/humaine:${PROD_TIMESTAMP}_ui"
    restart: always
    container_name: ui
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

volumes:
  humaine:
