version: "3.7"

services:
  ##############################
  # Backend Container
  ##############################
  api:
    env_file: "./API/.env"
    container_name: api
    restart: always
    image: "kanlanc/humaine:${PROD_TIMESTAMP}_api"
    ports:
      - "4000:4000"

  ##############################
  # UI Container
  ##############################
  ui:
    image: "kanlanc/humaine:${PROD_TIMESTAMP}_ui"
    restart: always
    container_name: ui
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    environment:
      API_URL: "/"
    # volumes:
    #   - ./UI/nginx/certbot/conf:/etc/letsencrypt
    #   - ./UI/nginx/certbot/www:/var/www/certbot

  # ##############################
  # # Certbot Container
  # ##############################
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./UI/nginx/certbot/conf:/etc/letsencrypt
  #     - ./UI/nginx/certbot/www:/var/www/certbot

volumes:
  humaine:
