export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const FORGET_PASSWORD_FAIL = 'FORGET_PASSWORD_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const GET_PROFILE = 'GET_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const CLEAR_FORGET_PASSWORD_ALERT = 'CLEAR_FORGET_PASSWORD_ALERT';
export const SET_FORGET_PASSWORD_ALERT = 'SET_FORGET_PASSWORD_ALERT';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
export const GET_MESSAGES = 'GET_MESSAGES';
export const ADD_DIAGNOSIS = 'ADD_DIAGNOSIS';
export const HIDE_DIAGNOSIS_RESULT = 'HIDE_DIAGNOSIS_RESULT';
export const FLAG_MESSAGE = 'FLAG_MESSAGE';
export const SHOW_LOADING = 'SHOW_LOADING';
export const IS_BOT_THINKING = 'IS_BOT_THINKING';

export const GET_NOTES = 'GET_NOTES';
export const SEND_NOTES_ERROR = 'SEND_NOTES_ERROR';
export const SAVE_NOTE = 'SAVE_NOTE';

export const GET_CASES = 'GET_CASES';
export const GET_CASE_INFO = 'GET_CASE_INFO';
export const APPEND_CHAT_MESSAGE = 'APPEND_CHAT_MESSAGE';

