#FROM postgres:13.3-alpine THis is not working with initialization

FROM postgres:13.2-alpine
COPY ./humaine_backup_latest.sql /docker-entrypoint-initdb.d/
#COPY ./humaine_backup_latest.sql /docker-entrypoint-initdb.d/



