FROM node:15-alpine3.10
ENV NODE_ENV development
LABEL version="1.0"
LABEL description="This is the base docker image for Humaine frontend react app."
LABEL maintainer = ["saivicky2015@gmail.com", "akashsmaran@gmail.com"]

WORKDIR /app

# COPY ["package.json", "package-lock.json", "./"]


RUN npm install -g nodemon 

# COPY . ./

EXPOSE 4000

CMD "npm" "run" "dev"